version: '3'

services:
  fedirun:
    restart: unless-stopped
    container_name: fedirun
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/app/config

# vim: tabstop=2 shiftwidth=2 expandtab
